[httpd]
enable_cors = true
bind_address = 0.0.0.0

[cors]
; Adjust origins to match your domain in production
origins = http://localhost:3000,http://localhost:3001,http://localhost:8080
credentials = true
methods = GET, PUT, POST, HEAD, DELETE
headers = accept, authorization, content-type, origin, referer
